dependencies = ["asgard-test", "asgard-backend"]
description = "A description"
destination_server = ["app-hosting-node", "database-hosting-node", "scalingo-platform"]
flags = ["deployed-by-chef", "devops", "global"]
languages = ["ansible", "dockerile"]
owner = "kein@scalingo.com"
team = "UFS"
version = "0.1"
