dependencies = ["asgard-cli"
description = "This is a description"
destination_server = ["database-hosting-node", "front", "internal"]
flags = ["deployed-by-chef", "lib", "sdk"]
languages = "ansible"]
owner = "siham@scalingo.com"
team = "Infosec"
version = "0.1"
