dependencies = ["asgard-test", "asgard-backend"]
description = ""
destination_server = ["app-hosting-node", "database-hosting-node", "scalingo-platform"]
flags = ["deployed-by-chef", "devops", "global"]
languages = ["ansible", "dockerfile"]
owner = "etienne@scalingo.com"
team = "IST"
version = "0.1"
